// ===========================================================================
// model.h — Exported Linear Regression Model for Edge AI Inference
// ===========================================================================
// Auto-generated by micromlgen from a scikit-learn LinearRegression model.
// Contains learned weights for predicting a continuous apnea risk score
// from three features: BPM, SpO2, and SpO2 drop.
// ===========================================================================

#pragma once
#include <cstdarg>

namespace Eloquent {
namespace ML {
namespace Port {

class LinearRegression {
public:
    /**
     * Predict continuous risk score based on feature vector
     */
    float predict(float *x) {
        return dot(x, 0.199234328306, -1.496480796637, 1.990071357998) + 137.82684058201806;
    }

protected:
    /**
     * Compute dot product of inputs and learned weights
     */
    float dot(float *x, ...) {
        va_list w;
        va_start(w, 3);
        float dot = 0.0;
        for (uint16_t i = 0; i < 3; i++) {
            const float wi = va_arg(w, double);
            dot += x[i] * wi;
        }
        return dot;
    }
};

} // namespace Port
} // namespace ML
} // namespace Eloquent